sudo: required
services:
  - docker

before_install:
  - docker build -t jjayoma2017/docker -f Dockerfile.dev .

script:
  - docker run -e CI=true jjayoma2017/docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-699422764057
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY
